duty day script
EyeSeeTea/ESTools pull request #129
Opened 2023-08-01 08:35 UTC by idelcano

https://app.clickup.com/t/865ct8tva

docker pull docker.eyeseetea.com/widpit/alpineupdated:latest

docker run -it --privileged --rm -e DISPLAY=$DISPLAY -v /tmp/.X11-unix:/tmp/.X11-unix --mount src="$(pwd)",target=/test_container,type=bind -p 8085:8080 docker.eyeseetea.com/widpit/alpineupdated

2023-10-11 13:46 UTC, ifoche requested changes
thanks @idelcano but could you please remove hostnames from it? config file you could put it as an example without any information and then we keep the actual file private

2024-01-17 11:27 UTC, nshandra requested changes
The script works and its a great tool. We both have used it so we know it works.

I have taken the liberty of adding a readme and making the changes to `config.json` requested by @ifoche.

My comments are mainly suggestions to consider implementing if there is some new feature added.

As for the requested changes:

- fix the typo
- rewrite the Spanish comments to English
- Check my `README.md` in case i missed something

All in all, good work.

2024-01-17 11:27 UTC, nshandra commented on DHIS2/dutyday/config.json
Maybe monit and diskspace can be merged in a single entry.

2024-01-17 11:27 UTC, nshandra commented on DHIS2/dutyday/logger.sh
> +}
The value of "monit" field could be used here. That way, if we needed to change the command there would be no need to redeploy logger.sh.

In the other hand that's probably unlikely.

2024-01-17 11:27 UTC, nshandra commented on DHIS2/dutyday/reporter.py
> +
I get why its hard-coded in the script, as we both use the same docker image, but in a generic case the key path and the username should be either command line arguments or in the config.json file.

Given the intended users of the script its fine like this.

2024-01-17 11:27 UTC, nshandra commented on DHIS2/dutyday/reporter.py
> +            # Accede a el Accede a elementos opcionales de manera segura
Typo?
Also, change to English

2024-01-17 11:27 UTC, nshandra commented on DHIS2/dutyday/logger.sh
> +    # Calcula la fecha de inicio basándose en los días hacia atrás
Change to English

2024-01-17 11:27 UTC, nshandra commented on DHIS2/dutyday/reporter.py
> +    path_to_private_key = '/root/.ssh/id_rsa'  # ruta a tu archivo de clave privada SSH
change comment to English

2024-03-27 11:16 UTC, merged